# fly.toml app configuration file generated for quizifyoffical on 2023-12-17T23:20:23-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quizifyoffical"
primary_region = "sea"

[env]
  PORT = "3001"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
